[project]
name = "tpu-module-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax[tpu]>=0.8.1",
    "ml-dtypes>=0.5.4",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
]
